### ISSUE TITLE
question about download data from TSDB

### ISSUE THREAD

**Issue by c0syfeng** [WenjieDu/TSDB#59]
### 1. System Info

hi,bro.ur work is very gorgeous,give me a convenient way to access dataset. there's a problem when i want to download **ucr_uea_Beef** from ur work. 
error  as follows:

2024-05-20 13:49:07 [INFO]: You're using dataset ucr_uea_Adiac, please cite it properly in your work. You can find its reference information at the below link: 
https://github.com/WenjieDu/TSDB/tree/main/dataset_profiles/ucr_uea_datasets
2024-05-20 13:49:07 [INFO]: Start downloading...
Traceback (most recent call last):
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/site-packages/tsdb/utils/downloading.py", line 56, in _download_and_extract
    urllib.request.urlretrieve(url, raw_data_saving_path)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ljf/ljf/data.py", line 4, in <module>
    tsdb.load('ucr_uea_Adiac')
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/site-packages/tsdb/data_processing.py", line 73, in load
    download_and_extract(dataset_name, dataset_saving_path)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/site-packages/tsdb/utils/downloading.py", line 103, in download_and_extract
    _download_and_extract(DATABASE[dataset_name], dataset_saving_path)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/site-packages/tsdb/utils/downloading.py", line 60, in _download_and_extract
    raise RuntimeError(f"Exception: {e}\n" f"Download failed. Aborting.")
RuntimeError: Exception: HTTP Error 403: 
Download failed. Aborting.

i try  under case that open VPN or off VPN. The error always be there.And my version of tsdb is 0.3.1.

looking for ward to ur reply.

### 2. Information

- [ ] The official example scripts
- [X] My own created scripts

### 3. Reproduction

tsdb.download_and_extract('ucr_uea_Beef','./TSLANet-main/beef')

2024-05-20 13:49:07 [INFO]: You're using dataset ucr_uea_Adiac, please cite it properly in your work. You can find its reference information at the below link: 
https://github.com/WenjieDu/TSDB/tree/main/dataset_profiles/ucr_uea_datasets
2024-05-20 13:49:07 [INFO]: Start downloading...
Traceback (most recent call last):
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/site-packages/tsdb/utils/downloading.py", line 56, in _download_and_extract
    urllib.request.urlretrieve(url, raw_data_saving_path)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ljf/ljf/data.py", line 4, in <module>
    tsdb.load('ucr_uea_Adiac')
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/site-packages/tsdb/data_processing.py", line 73, in load
    download_and_extract(dataset_name, dataset_saving_path)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/site-packages/tsdb/utils/downloading.py", line 103, in download_and_extract
    _download_and_extract(DATABASE[dataset_name], dataset_saving_path)
  File "/home/ljf/miniconda3/envs/pytorch/lib/python3.7/site-packages/tsdb/utils/downloading.py", line 60, in _download_and_extract
    raise RuntimeError(f"Exception: {e}\n" f"Download failed. Aborting.")
RuntimeError: Exception: HTTP Error 403: 
Download failed. Aborting.

### 4. Expected behavior

i expect for dataset in tsdb

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to TSDB and PyPOTS! You can follow me on GitHub to receive the latest news of TSDB and PyPOTS. If you find TSDB helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
Hi @c0syfeng, their timeseriesclassification.com site was under maintenance. The site now is back, and tsdb now works for me. Please give it a try on your side with `tsdb.load("ucr_uea_Beef")`.
